
dist: trusty
sudo: false

language: go

go:
  - 1.11.2

env:
  - GOMAXPROCS=4

branches:
  only:
    - master

env:
  - CONSUL_VERSION=1.4.0

before_install:
  - curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul.zip
  - mkdir -p ~/bin
  - mv consul ~/bin
  - export PATH="~/bin:$PATH"
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script: make test